##
# Minimal Playbook
#
# @author Akafael
##
---
- hosts: localhost
  connection: local
  become: yes
  vars:
    ansible_python_interpreter: /usr/local/bin/python2.7
  tasks:
  - name: Ensure all packages are installed
    ansible.builtin.package:
      name: firefox
      state: present
