##
# Minimal Playbook
#
# @author Akafael
##
---
- name: Prepare a basic Enviroment
  hosts: localhost
  connection: local
  become: true

  roles:
    - { role: desktop, tags: ['desktop'] }
    - { role: arduino, tags: ['dev'] }

