##
# Minimal Playbook
#
# @author Akafael
##
---
- hosts: localhost
  connection: local
  become: yes
  tasks:
  - name: Ensure all packages are installed
    ansible.builtin.package:
      name: firefox
      state: present
