name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Display help
      run: make help

    - name: Install dependencies
      run: make install

    - name: Check if the playbook is properly working
      run: make check

    - name: Run Playbook
      run: make run